use_frameworks!

platform :ios, '9.0'

target 'XWUIKitCategory_Example' do
  pod 'XWUIKitCategory', :path => '../'

  target 'XWUIKitCategory_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
